version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fullcycle-node-app
    # entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s docker-entrypoint.sh
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: fullcycle-mysql
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    volumes:
      - ./mysql/data/mydatabase:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: fullcycle-nginx
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - node-app

networks:
  app-network:
